# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("echo.proto", :syntax => :proto3) do
    add_message "echo.EchoRequest" do
      optional :message, :string, 1
    end
    add_message "echo.EchoResponse" do
      optional :message, :string, 1
    end
  end
end

module Echo
  EchoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("echo.EchoRequest").msgclass
  EchoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("echo.EchoResponse").msgclass
end
